### ISSUE TITLE
Change second test RD value

### ISSUE THREAD

**Issue by alocate** [w3champions/w3champions-mmr-service#3]
@Qeenon thanks a lot for adding those tests, indeed it's much better with it and is/will be useful when we add complexity.

Could you change the second test so that the pre-game rd is not equal to "30"? Currently, with how we use Glicko2 (choice of parameters), RD cannot become smaller than 60.25 so it's not really relevant to use this value. As you can see, even in that case, we return a new RD which is greater than 60.25, so it's not supposed to ever happen that it's smaller to begin with.

**Comment by Qeenon** [comment]
@alocate I'd like to know more how everything works, specially finding pairs for games, I will do that change. Alike if RD there will be 90 after such game it's still being 90, it's okay?
